name: Run Script
on: workflow_dispatch # Adds a manual "Run" button

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run main.py
        run: python main.py
